added links
Morbit/TaskManager pull request #11
Opened 2021-08-31 19:33 UTC by Morbit

2021-09-01 17:46 UTC, greybutton requested changes

2021-09-01 17:46 UTC, greybutton commented on config/routes.rb
> +    resource :boards, only: :show
почему изменил?

2021-09-01 18:50 UTC, Morbit commented on config/routes.rb
> +    resource :boards, only: :show
Если кратко — по-другому не работало :-)
В поиске решения проблемы я нашел в чате обучения вот это:
![image](https://user-images.githubusercontent.com/1647208/131727066-95095c10-5e75-4960-843c-a8d4a82f0c1b.png)

Не совсем про то, конечно. Но после того как я поменял на boards в нескольких местах все заработало. Должно быть в единственном числе?

2021-09-01 19:05 UTC, greybutton commented on config/routes.rb
> +    resource :boards, only: :show
можно оставить как есть или вернуть `resource :board` и поменять `root :to => "web/board#show"`

2021-10-05 19:44 UTC, Morbit commented on config/routes.rb
> +    resource :boards, only: :show
Вернул board.

2021-10-06 19:05 UTC, greybutton approved these changes

2021-11-22 21:54 UTC, merged