Feature/admin
Morbit/TaskManager pull request #12
Opened 2021-11-11 19:48 UTC by Morbit

2021-11-15 19:59 UTC, greybutton requested changes

2021-11-15 19:59 UTC, greybutton commented on app/views/admin/users/edit.html.slim
> +  = render :partial => 'form', locals: { f: f }
форма немного разорванной получается, можно весь симпл форм убрать в _form и прокидывать из edit/new нужный url

2021-11-15 19:59 UTC, greybutton commented on test/factories/users.rb
> -    end
почему удалил и добавил test/factories/admins.rb?

2021-11-16 18:05 UTC, Morbit commented on app/views/admin/users/edit.html.slim
> +  = render :partial => 'form', locals: { f: f }
Поправил. Вроде ок. Юзеры создаются и редактируются

2021-11-16 20:08 UTC, greybutton approved these changes

2021-11-22 21:54 UTC, merged