WIP: Feature/tasks
Morbit/TaskManager pull request #16
Opened 2021-11-22 21:56 UTC by Morbit

2021-11-29 20:11 UTC, greybutton requested changes

2021-11-29 20:11 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +      order(sort)
сортировку не задаем в контроллере, она через рансак будет выбираться

2021-11-29 20:11 UTC, greybutton commented on package.json
> +    "@lourenci/react-kanban": "^2.1.0",
это можно удалить, оставить @asseinfo/react-kanban

2021-12-02 20:10 UTC, Morbit commented on app/controllers/api/v1/tasks_controller.rb
> +      order(sort)
переделал, [так норм](https://github.com/Morbit/TaskManager/pull/16/commits/dd57754f43228a2ed3ea18839a7907c67c33a858)?

2021-12-03 06:47 UTC, greybutton approved these changes

2021-12-03 08:49 UTC, merged