added session
Morbit/TaskManager pull request #9
Opened 2021-08-31 19:13 UTC by Morbit

2021-09-01 17:43 UTC, greybutton requested changes

2021-09-01 17:43 UTC, greybutton commented on app/forms/session_form.rb
> +  end
проверь плис отступы, съехало немного

2021-09-01 17:43 UTC, greybutton commented on test/controllers/web/sessions_controller_test.rb
>  end
здесь нужно добавить тесты внутрь `Web::SessionsControllerTest`, удалять ничего не нужно 

`require 'test_helper'` вернуть

2021-10-06 19:02 UTC, greybutton approved these changes
проверь рубокоп плис

2021-10-06 19:02 UTC, greybutton commented on config/routes.rb
>      resource :session, only: :new
эту строчку можно удалить, одна строчка с resource :session должна остаться

2021-10-28 18:52 UTC, Morbit commented on config/routes.rb
>      resource :session, only: :new
удалил, замечания рубокопа пофиксил

2021-11-22 21:55 UTC, merged